### PR TITLE
Protocol41150

### PR DESCRIPTION
**Pull request by blackheart01**
I did a vimdiff to compare protocol40336.py with protocol41150.py and applied the same changes to protocol40336.js to make protocol41150.js. I also updated the version and patch numbers.

### CODE REVIEW

**Comment by blackheart01** [comment]
I also downloaded a replay for protocol 41150 and tested with the --details --json parameters.

**Comment by jnovack** [comment]
AWESOME!  You may also wish to contribute to the initial library this is a fork of.

https://github.com/Farof/heroprotocoljs

**Comment by blackheart01** [comment]
Ha, that makes sense! I hadn't even noticed it was a fork of Farof/heroprotocoljs! It even says it in the description of the project!

**Comment by jnovack** [comment]
I only forked it because I needed to integrate my c++ extraction library rather than using the javascript extraction library.  But now that he's integrated an api so I can extract via c++ and parse via js.

**Pull request merged**
